version: '3'
services:
  mysql_go_todo_list:
    image: mysql:8.0.32-oracle
    container_name: mysql_go_todo_list
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - networks_go_todo_list
    volumes:
      - mysql_go_todo_list:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD : ROOT
       MYSQL_PASSWORD : SECRET  
       MYSQL_USER : ADMIN
       MYSQL_DATABASE : todo4

  go_todo_list:
    build: .
    image: go_todo_list
    container_name: go_todo_list
    networks:
      - networks_go_todo_list
    ports:
      - 8090:3030
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql_go_todo_list
    restart: on-failure
    depends_on:
      - mysql_go_todo_list
  
  
volumes:
  mysql_go_todo_list: {}

networks:
  networks_go_todo_list: {}
  